export const UNIVERSITIES = [
  // United States
  "Harvard University",
  "Stanford University",
  "MIT",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Chicago",
  "Duke University",
  "Northwestern University",
  "Caltech",
  "Johns Hopkins University",
  "Dartmouth College",
  "Brown University",
  "Cornell University",
  "Rice University",
  "Vanderbilt University",
  "University of Pennsylvania",
  "University of Notre Dame",
  "Georgetown University",
  "University of California, Berkeley",
  "UCLA",
  "University of Michigan",
  "University of Virginia",
  "Carnegie Mellon University",
  "University of Southern California",
  "New York University",
  "Boston University",
  "University of Texas at Austin",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Ohio State University",
  "Penn State University",
  "University of Florida",
  "University of Illinois Urbana-Champaign",
  "Georgia Tech",
  "University of North Carolina at Chapel Hill",
  "University of Arizona",
  "Arizona State University",
  "University of Colorado Boulder",
  "University of Maryland",
  "Indiana University",
  "Purdue University",
  "University of Minnesota",
  "Rutgers University",
  "University of Pittsburgh",
  "University of Oregon",
  "University of Iowa",
  "University of Kansas",
  "University of Oklahoma",

  // United Kingdom
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London",
  "London School of Economics",
  "King's College London",
  "University of Edinburgh",
  "University of Manchester",
  "University of Bristol",
  "University of Warwick",
  "University of Glasgow",
  "Durham University",
  "University of Birmingham",
  "University of Leeds",
  "University of Sheffield",
  "University of Nottingham",
  "University of Southampton",
  "Queen Mary University of London",

  // Canada
  "University of Toronto",
  "McGill University",
  "University of British Columbia",
  "University of Alberta",
  "University of Waterloo",
  "McMaster University",
  "Université de Montréal",
  "Western University",
  "Queen's University",

  // Europe
  "ETH Zurich",
  "EPFL",
  "Sorbonne University",
  "Sciences Po",
  "Technical University of Munich",
  "Ludwig Maximilian University of Munich",
  "Heidelberg University",
  "Humboldt University of Berlin",
  "KU Leuven",
  "Delft University of Technology",
  "University of Amsterdam",
  "Utrecht University",
  "Karolinska Institute",
  "KTH Royal Institute of Technology",
  "Lund University",
  "University of Copenhagen",
  "University of Helsinki",
  "Trinity College Dublin",
  "Polytechnic University of Milan",
  "Sapienza University of Rome",
  "University of Bologna",
  "Pompeu Fabra University",
  "Autonomous University of Madrid",
  "University of Barcelona",
  "University of Vienna",
  "University of Warsaw",

  // Asia
  "National University of Singapore",
  "Nanyang Technological University",
  "Tsinghua University",
  "Peking University",
  "Fudan University",
  "Shanghai Jiao Tong University",
  "Zhejiang University",
  "University of Hong Kong",
  "Hong Kong University of Science and Technology",
  "Chinese University of Hong Kong",
  "University of Tokyo",
  "Kyoto University",
  "Osaka University",
  "Tokyo Institute of Technology",
  "Seoul National University",
  "KAIST",
  "Yonsei University",
  "Korea University",
  "Taiwan University",

  // India
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IISc Bangalore",
  "BITS Pilani",
  "Delhi University",
  "Jawaharlal Nehru University",
  "University of Mumbai",
  "Anna University",
  "Jadavpur University",
  "Banaras Hindu University",
  "Manipal Academy of Higher Education",
  "VIT Vellore",
  "Amity University",
  "SRM Institute of Science and Technology",

  // Pakistan
  "LUMS",
  "NUST Islamabad",
  "Quaid-i-Azam University",
  "University of the Punjab",
  "Aga Khan University",

  // Middle East
  "King Abdulaziz University",
  "King Saud University",
  "American University of Beirut",
  "Tel Aviv University",
  "Hebrew University of Jerusalem",
  "Technion - Israel Institute of Technology",
  "Bilkent University",
  "Bogazici University",
  "Koc University",

  // Australia & New Zealand
  "University of Melbourne",
  "Australian National University",
  "University of Sydney",
  "University of Queensland",
  "Monash University",
  "University of New South Wales",
  "University of Western Australia",
  "University of Adelaide",
  "University of Auckland",

  // Latin America
  "University of São Paulo",
  "University of Buenos Aires",
  "UNAM",
  "Tecnológico de Monterrey",
  "Pontifical Catholic University of Chile",
  "University of Chile",

  // Africa
  "University of Cape Town",
  "University of the Witwatersrand",
  "Stellenbosch University",
  "Cairo University",
  "American University in Cairo",
  "University of Lagos",
  "University of Nairobi",

  "Other",
] as const;

export type University = typeof UNIVERSITIES[number];
