export const UNIVERSITIES = [
  "Harvard University",
  "Stanford University",
  "MIT",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Chicago",
  "Duke University",
  "Northwestern University",
  "Caltech",
  "Johns Hopkins University",
  "Dartmouth College",
  "Brown University",
  "Cornell University",
  "Rice University",
  "Vanderbilt University",
  "University of Pennsylvania",
  "University of Notre Dame",
  "Georgetown University",
  "University of California, Berkeley",
  "UCLA",
  "University of Michigan",
  "University of Virginia",
  "Carnegie Mellon University",
  "University of Southern California",
  "New York University",
  "Boston University",
  "University of Texas at Austin",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Ohio State University",
  "Penn State University",
  "University of Florida",
  "University of Illinois Urbana-Champaign",
  "Georgia Tech",
  "University of North Carolina at Chapel Hill",
  "University of Arizona",
  "Arizona State University",
  "University of Colorado Boulder",
  "University of Maryland",
  "Indiana University",
  "Purdue University",
  "University of Minnesota",
  "Rutgers University",
  "University of Pittsburgh",
  "University of Oregon",
  "University of Iowa",
  "University of Kansas",
  "University of Oklahoma",
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London",
  "London School of Economics",
  "King's College London",
  "University of Edinburgh",
  "University of Manchester",
  "University of Bristol",
  "University of Warwick",
  "University of Glasgow",
  "Durham University",
  "University of Birmingham",
  "University of Leeds",
  "University of Sheffield",
  "University of Nottingham",
  "University of Southampton",
  "Queen Mary University of London",
  "University of Toronto",
  "McGill University",
  "University of British Columbia",
  "University of Alberta",
  "University of Waterloo",
  "McMaster University",
  "Université de Montréal",
  "Western University",
  "Queen's University",
  "ETH Zurich",
  "EPFL",
  "Sorbonne University",
  "Sciences Po",
  "Technical University of Munich",
  "Ludwig Maximilian University of Munich",
  "Heidelberg University",
  "Humboldt University of Berlin",
  "KU Leuven",
  "Delft University of Technology",
  "University of Amsterdam",
  "Utrecht University",
  "Karolinska Institute",
  "KTH Royal Institute of Technology",
  "Lund University",
  "University of Copenhagen",
  "University of Helsinki",
  "Trinity College Dublin",
  "Polytechnic University of Milan",
  "Sapienza University of Rome",
  "University of Bologna",
  "Pompeu Fabra University",
  "Autonomous University of Madrid",
  "University of Barcelona",
  "University of Vienna",
  "University of Warsaw",
  "National University of Singapore",
  "Nanyang Technological University",
  "Tsinghua University",
  "Peking University",
  "Fudan University",
  "Shanghai Jiao Tong University",
  "Zhejiang University",
  "University of Hong Kong",
  "Hong Kong University of Science and Technology",
  "Chinese University of Hong Kong",
  "University of Tokyo",
  "Kyoto University",
  "Osaka University",
  "Tokyo Institute of Technology",
  "Seoul National University",
  "KAIST",
  "Yonsei University",
  "Korea University",
  "Taiwan University",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IISc Bangalore",
  "BITS Pilani",
  "Delhi University",
  "Jawaharlal Nehru University",
  "University of Mumbai",
  "Anna University",
  "Jadavpur University",
  "Banaras Hindu University",
  "Manipal Academy of Higher Education",
  "VIT Vellore",
  "Amity University",
  "SRM Institute of Science and Technology",
  "LUMS",
  "NUST Islamabad",
  "Quaid-i-Azam University",
  "University of the Punjab",
  "Aga Khan University",
  "King Abdulaziz University",
  "King Saud University",
  "American University of Beirut",
  "Tel Aviv University",
  "Hebrew University of Jerusalem",
  "Technion - Israel Institute of Technology",
  "Bilkent University",
  "Bogazici University",
  "Koc University",
  "University of Melbourne",
  "Australian National University",
  "University of Sydney",
  "University of Queensland",
  "Monash University",
  "University of New South Wales",
  "University of Western Australia",
  "University of Adelaide",
  "University of Auckland",
  "University of São Paulo",
  "University of Buenos Aires",
  "UNAM",
  "Tecnológico de Monterrey",
  "Pontifical Catholic University of Chile",
  "University of Chile",
  "University of Cape Town",
  "University of the Witwatersrand",
  "Stellenbosch University",
  "Cairo University",
  "American University in Cairo",
  "University of Lagos",
  "University of Nairobi",
  "AAFT University of Media and Arts",
  "ABES Engineering College, Ghaziabad",
  "Abhilashi University",
  "Achariya College of Engineering Technology",
  "Acropolis Group of Institutions, Indore",
  "Acropolis Institute of Technology & Research",
  "Adamas University, Kolkata",
  "Aditya Engineering College",
  "Agnel Polytechnic, South Goa",
  "AKS University",
  "Aligarh Muslim University",
  "Alliance College of Engineering and Design, Bangalore",
  "Alliance University, Bangalore",
  "Alpha College of Engineering & Technology, Pondicherry",
  "Amal Jyothi College of Engineering",
  "Amity University, Gurgaon",
  "Amity University, Gwalior",
  "Amity University, Jaipur",
  "Amity University, Kolkata",
  "Amity University, Mumbai",
  "Amity University, Noida",
  "Amity University, Patna",
  "Amity University, Raipur",
  "Amity University, Ranchi",
  "Amritsar College of Engineering and Technology",
  "Andhra University, College of Engineering",
  "Anurag University, Hyderabad",
  "Apex Institute of Technology",
  "Apex Professional University",
  "APJ Abdul Kalam Technological University",
  "Arka Jain University, Jamshedpur",
  "Army Institute of Technology",
  "Arni University, Kangra",
  "Artex Informatic Solutions, Chandigarh",
  "Arunachal University of Studies",
  "Arunodaya University, Itanagar",
  "Aryabhatta Knowledge University",
  "Asansol Engineering College",
  "Assam Don Bosco University",
  "Assam Down Town University",
  "Assam Engineering College",
  "Assam Engineering Institute",
  "Assam Institute of Technology",
  "Assam Science and Technology University",
  "Assam University, Silchar",
  "Atal Bihari Vajpayee Indian Institute of Information",
  "Auro University, Surat",
  "Avantika University, Ujjain",
  "Awadhesh Pratap Singh University",
  "B. Borooah College, Guwahati",
  "B.S. Abdur Rahman Crescent Institute of Science",
  "Baba Banda Singh Bahadur Engineering College",
  "Baba Ghulam Shah Badshah University",
  "Baddi University of Emerging Sciences and Technologies",
  "Bahra University",
  "Bakhtiyarpur College of Engineering",
  "Banasthali Vidyapith, Jaipur",
  "Bannari Amman Institute of Technology",
  "Bapatla Engineering College",
  "Barak Valley Engineering College",
  "Basaveshwar Engineering College",
  "Baselios Thomas I Catholicose College of Engineering",
  "Bells Institute of Management & Technology, Shimla",
  "Bengal College of Engineering",
  "Bengal College of Engineering and Technology",
  "Bengal Institute of Technology",
  "Bennett University, Greater Noida",
  "BFIT Group of Institutions",
  "Bhagalpur College of Engineering",
  "Bharathiyar College of Engineering and Technology",
  "Bharati Vidyapeeth Deemed University",
  "Bhargava College of Engineering & Technology",
  "Bhilai Institute of Technology",
  "Bhubaneswar Engineering College",
  "Biju Patnaik University of Technology",
  "Bineswar Brahma Engineering College- [BBEC], Kokrajhar",
  "Bipin Tripathi Kumaon Institute of Technology, Almora",
  "Bir Tikendrajit University, Imphal",
  "Birla Institute of Technology",
  "Birla Institute of Technology and Science",
  "Birla Institute of Technology Extension Centre",
  "Birsa Institute of Technology",
  "BMS College of Engineering",
  "BMS Institute of Technology and Management",
  "Bundelkhand Institute of Engineering & Technology",
  "BV Raju Institute of Technology",
  "C. U. Shah University, Wadhwan",
  "C. V. Raman Global University, Bhubaneswar",
  "Cambridge Institute of Technology",
  "Capital University",
  "Career Point University",
  "Central Agricultural University",
  "Central Institute of plastics engineering & Technology-",
  "Central Institute of Plastics Engineering and Technology",
  "Central Institute of Technology",
  "Central University of Jammu, Jammu",
  "Central University of Kashmir",
  "Centurion University of Technology and Management",
  "CEPT University, Ahmedabad",
  "Chaibasa Engineering College, Techno India Group, Chaibasa",
  "Chaitanya Bharathi Institute of Technology",
  "Chandigarh College of Engineering and Technology",
  "Chandigarh Engineering College",
  "Chandigarh Group of Colleges",
  "Chhatrapati Shivaji Institute of Technology",
  "Chhattisgarh Engineering College",
  "Chhotu Ram Rural Institute Of Technology",
  "Chitkara University",
  "Chitkara University, Solan",
  "Chouksey Engineering College",
  "Christ College of Engineering and Technology, Pondicherry",
  "Christ Institute of Technology",
  "Christ University, Bangalore",
  "Christian College of Engineering and Technology",
  "CIPET: Centre for Skilling and Technical Support",
  "Cluster University of Srinagar",
  "CMJ University, Ri-Bhoi",
  "CMR Engineering College",
  "CMR Institute of Technology",
  "Cochin University of Science and Technology",
  "Cochin University of Science and Technology, School",
  "Coimbatore Institute of Technology",
  "College of Agricultural Engineering and Post Harvest Technology",
  "College of Engineering",
  "College of Engineering and Technology",
  "College of Engineering Thalassery, Kannur",
  "College of Engineering, Anna University",
  "College of Engineering, Trivandrum",
  "College of Technology, GB Pant University of",
  "Columbia Institute of Engineering and Technology",
  "CSIR-Institute of Minerals and Materials Technology -[CSIR-IMMT]",
  "CVR College of Engineering, Ibrahimpatnam, Rangareddi",
  "Darbhanga College of Engineering",
  "DAV University, Jalandhar",
  "Dayalbagh Educational Institute Faculty of Engineering, Agra",
  "Dayananda Sagar College of Engineering",
  "Defence Institute of Advanced Technology",
  "Delhi Technical Campus",
  "Delhi Technological University",
  "Dev Bhoomi Institute of Technology",
  "Dharmsinh Desai University",
  "Dhirubhai Ambani Institute of Information and Communication",
  "Dibrugarh Polytechnic",
  "Dibrugarh University, Dibrugarh",
  "Disha Institute of Management and Technology",
  "DIT University",
  "Don Bosco College of Engineering and Technology",
  "Doon University, Dehradun",
  "Dr BR Ambedkar National Institute of Technology",
  "Dr. Ambedkar Institute of Technology",
  "Dr. B R Ambedkar Institute of Technology, Port Blair",
  "Dr. B. R. Ambedkar Polytechnic College",
  "Dr. B.C. Roy Engineering College",
  "Dr. S. S. Bhatnagar University Institute of",
  "Duliajan College, Dibrugarh",
  "Dwarkadas J Sanghvi College of Engineering",
  "Eternal University",
  "Faculty of Engineering and Technology, Jain University",
  "Faculty of Technology and Engineering, Maharaja Sayajirao",
  "Federal Institute of Science and Technology",
  "G. Pulla Reddy Engineering College",
  "Galgotias University",
  "Gandhi Institute for Technology",
  "Ganpat University",
  "Gauhati University",
  "Gaya College of Engineering, Gaya",
  "Gayatri Vidya Parishad College of Engineering",
  "GH Raisoni College of Engineering",
  "Girijananda Chowdhury Institute of Management & Technology",
  "GITA Autonomous College",
  "GLA University, Mathura",
  "Global Institute, Amritsar",
  "Glocal University, Saharanpur",
  "Goa College of Engineering",
  "Goa University, North Goa",
  "Gokaraju Rangaraju Institute of Engineering and Technology",
  "Government College of Engineering and Technology",
  "Government College of Engineering, Kendujhar",
  "Government College of Technology",
  "Government Degree College for Boys, Udhampur",
  "Government Engineering College",
  "Government Industrial Training Institute",
  "Government Polytechnic",
  "Government Polytechnic College",
  "Government Polytechnic College -[GPC], Anantnag",
  "Government Polytechnic College, Bandipora",
  "Government Polytechnic College, Baramulla",
  "Government Polytechnic College, Budgam",
  "Government Polytechnic College, Sopore",
  "Government Polytechnic for Women",
  "Government Polytechnic For Women-[GPW], Jammu",
  "Government Polytechnic Kargil, Kargil",
  "Government Polytechnic Laying, Itanagar",
  "Government Polytechnic Roing, Roing",
  "Government Polytechnic Sedem, Tuensang",
  "Government Polytechnic Seithekema C, Dimapur",
  "Government Polytechnic Tsunazho",
  "Government Polytechnic, Bicholim",
  "Government Polytechnic, Curchorem",
  "Government Polytechnic, Daman",
  "Government Polytechnic, Imphal",
  "Government Polytechnic, Kohima",
  "Government Polytechnic, Kulgam",
  "Govind Ballabh Pant Engineering College",
  "Govt Engineering College, Bilaspur",
  "Govt. Gandhi Memorial Science College, Jammu",
  "Graphic Era Hill University",
  "Graphic Era Hill University Bhimtal Campus",
  "Graphic Era University",
  "Graphic Era University, School of Engineering and",
  "Green Hills Engineering College, Solan",
  "GSFC University, Vadodara",
  "Gudlavalleru Engineering College",
  "Guru Gobind Singh Indraprastha University",
  "Guru Kashi University, Bathinda",
  "Guru Nanak Dev Engineering College",
  "Gurugram University, Gurgaon",
  "Gurukul Vidyapeeth, Chandigarh",
  "Haldia Institute of Technology",
  "Harcourt Butler Technological University",
  "Heritage Institute of Technology",
  "Himachal Institute of Engineering and Technology",
  "Himalayan Group of Professional Institutions, Sirmaur",
  "Himalayan University",
  "Himgiri Zee University",
  "Hindustan College of Engineering",
  "Hindustan Institute of Technology and Science",
  "I.K. Gujral Punjab Technical University",
  "ICFAI University, Baddi",
  "ICFAI University, Dehradun",
  "ICFAI University, Raipur",
  "ICFAI University, West Tripura",
  "IEC University Baddi",
  "IFTM University, Moradabad",
  "IILM University, Gurgaon",
  "IIS (Deemed to be University)",
  "IITT Institutions, Chandigarh",
  "Indian Institute of Aeronautical Engineering",
  "Indian Institute of Chemical Technology",
  "Indian Institute of Engineering Science and Technology",
  "Indian Institute of Information Technology",
  "Indian Institute of Information Technology -[IIIT], Bhopal",
  "Indian Institute of Information Technology [IIIT], Kottayam",
  "Indian Institute of Information Technology Design and",
  "Indian Institute of Information Technology Sri City",
  "Indian Institute of Information Technology Vadodara",
  "Indian Institute of Science",
  "Indian Institute of Space Science and Technology",
  "Indian Institute of Technology",
  "Indian Institute of Technology Madras",
  "Indira Gandhi Delhi Technical University For Women",
  "Indira Gandhi Institute of Technology- [IGIT], Dhenkanal",
  "Indira Gandhi National Forest Academy",
  "Indira Gandhi Polytechnic College",
  "Indo Swiss Training Centre",
  "Indraprastha Institute of Information Technology",
  "Indraprastha Institute of Technology and Management",
  "Indus International University",
  "Indus University, Ahmedabad",
  "Institute of Advanced Studies in Education",
  "Institute of Aeronautical Engineering",
  "Institute of Chemical Technology",
  "Institute of Communication and Information Technology, Kohima",
  "Institute of Engineering and Management",
  "Institute of Engineering and Technology",
  "Institute of Engineering and Technology, Devi Ahilya",
  "Institute of Information Technology & Management",
  "Institute of Infrastructure Technology Research and Management",
  "Institute of Technical Education and Research",
  "Institute of Technology, Nirma University, Ahmedabad",
  "Integral University, Lucknow",
  "International Institute of Hotel Management",
  "International Institute of Information Technology",
  "Islamic University of Science and Technology",
  "ITM University, Raipur",
  "J.C. Bose University Of Science And Technology",
  "J.S. University",
  "Jabalpur Engineering College",
  "Jagannath University, Jaipur",
  "Jagran Lakecity University",
  "Jaipur Engineering College and Research Centre, Jaipur",
  "Jaipur National University",
  "Jalpaiguri Government Engineering College",
  "Jamia Millia Islamia University-[JMI], New Delhi",
  "Jawaharlal Nehru Government Engineering College",
  "Jawaharlal Nehru Technological University",
  "Jaypee Institute of Information Technology University",
  "Jaypee University of Engineering and Technology",
  "Jaypee University of Information Technology",
  "JECRC University",
  "Jharkhand Rai University",
  "JIS College of Engineering",
  "JNTUA College of Engineering, Ananthapur",
  "JNTUK University College of Engineering, Kakinada, East",
  "Jorhat Engineering College",
  "Jorhat Institute of Science and Technology",
  "Jowai Polytechnic, Jowai",
  "K L University",
  "K. J. Somaiya College of Engineering",
  "Kakatiya Institute of Technology & Science",
  "Kalyani Government Engineering College",
  "Karaikal Polytechnic College",
  "Karunya Institute of Technology and Sciences",
  "Kashmir Government Polytechnic",
  "Katihar Engineering College",
  "Kaziranga University",
  "Keshav Memorial Institute of Technology",
  "Khelhoshe Polytechnic Atoizu[KPA], Kohima",
  "Kirodimal Institute of Technology, Raigarh",
  "Kite Polytechnic College, Budgam",
  "KK College of Engineering and Management, Dhanbad",
  "KLE Technological University, Hubli",
  "KMCT College of Engineering, Kozhikode",
  "Kongu Engineering College",
  "Krishna Engineering College",
  "Krupajal Engineering College",
  "Kumaraguru College of Technology",
  "L.D. College of Engineering",
  "Lakhmi Chand Institute of Technology",
  "Lakshmi Narain College of Technology",
  "Lingaya's Vidyapeeth, Faridabad",
  "LNCT University",
  "Loknayak Jai Prakash Institute Of Technology",
  "Longowal Polytechnic College, Chandigarh",
  "LR Institute of Engineering and Technology, Solan",
  "Madhav University",
  "Maharaja Agrasen Institute of Technology",
  "Maharaja Agrasen University",
  "Maharaja Ranjit Singh Punjab Technical University, Bathinda",
  "Maharaja Surajmal Institute of Technology",
  "Maharana Pratap University of Agriculture and Technology",
  "Maharishi Markandeshwar",
  "Mahatma Gandhi Government Engineering College",
  "Mahatma Gandhi Institute of Technology",
  "Mahatma Gandhi University",
  "Mahindra University, Hyderabad",
  "Malaviya National Institute of Technology",
  "Malla Reddy College of Engineering",
  "Malla Reddy Engineering College",
  "Manakula Vinayagar Institute of Technology",
  "Manav Bharti University",
  "Manav Rachna International Institute Of Research And",
  "Manav Rachna University",
  "Mangalam College of Engineering Ettumanoor",
  "Manipal Institute of Technology",
  "Manipal University",
  "Manipur Institute of Technology",
  "Manipur Technical University",
  "Manipur University",
  "Mar Athanasius College of Engineering",
  "Marian Engineering College",
  "Maryland Institute of Technology And Management, Jamshedpur",
  "Masterpro Institute of Technology, Srinagar",
  "Matrusri Engineering College, Hyderabad",
  "Maulana Abul Kalam Azad University of Technology",
  "Maulana Azad College of Engineering and Technology",
  "Maulana Azad National Institute of Technology",
  "MBS College of Engineering and Technology, Jammu",
  "MEA Engineering College- [MEAEC], Malappuram",
  "Mepco Schlenk Engineering College, Sivakasi",
  "Millia Institute of Technology",
  "MIT University, Shillong",
  "MIT World Peace University",
  "Mizoram Polytechnic, Lunglei",
  "Mizoram University",
  "Mizoram University, School of Engineering and Technology",
  "MKSSS's Cummins College of Engineering for Women",
  "MLR Institute of Technology",
  "MNNIT Allahabad",
  "Modern Vidya Niketan",
  "Monad University, Hapur",
  "Morph Academy, Chandigarh",
  "MotherHood University, Roorkee",
  "Motihari College of Engineering",
  "Motilal Nehru Government Polytechnic College, Pondicherry",
  "Mukesh Patel School of Technology Management and",
  "Muzaffarpur Institute of Technology",
  "Nagaland University, Zunhebotto",
  "Nalanda College of Engineering",
  "Narula Institute of Technology",
  "National Centre for Antarctic and Ocean Research",
  "National Institute of Electronics & Information Technology",
  "National Institute of Food Technology Entrepreneurship and",
  "National Institute of Foundry & Forge Technology",
  "National Institute of Industrial Engineering",
  "National Institute of Oceanography",
  "National Institute of Science and Technology",
  "National Institute of Technical Teachers Training and",
  "National Institute of Technology",
  "Navrachana University",
  "Netaji Subhas Institute of Technology",
  "Netaji Subhas University",
  "Netaji Subhas University of Technology",
  "NETES Institute of Technology and Science",
  "New Horizon College of Engineering",
  "Nilai Institute of Technology",
  "Nirma University",
  "NIT Trichy, Tiruchirappalli",
  "Nitte Meenakshi Institute of Technology",
  "NMAM Institute of Technology",
  "Noida Institute of Engineering and Technology",
  "North East Frontier Technical University",
  "North Eastern Regional Institute of Science and Technology",
  "North-Eastern Hill University",
  "NSS College of Engineering",
  "OP Jindal University",
  "OPJS University, Churu",
  "Oriental University",
  "Orissa Engineering College",
  "P.P. Savani University, Surat",
  "P.S.G College of Technology",
  "Pacific University, Udaipur",
  "Padre Conceicao College of Engineering, Salcete",
  "Pandit Deendayal Petroleum University [PDPU] / (Energy",
  "Pandit Deendayal Petroleum University, School of Technology",
  "Panjab University",
  "Parala Maharaja Engineering College",
  "PDM University, Bahadurgarh, Bahadurgarh",
  "Perunthalaivar Kamarajar Institute of Engineering and Technology",
  "PES College of Engineering",
  "PES University",
  "PG Government College for Girls, Chandigarh",
  "Pimpri Chinchwad College of Engineering",
  "Plaksha, Mohali",
  "Plastindia International University, Dadra & Nagar Haveli",
  "Pondicherry Engineering College",
  "Pondicherry University",
  "Poornima College of Engineering, Jaipur",
  "Pragjyotish College, Guwahati",
  "Prasad V. Potluri Siddhartha Institute of Technology",
  "Presidency University, Bangalore",
  "PSV College of Engineering and Technology, Pondicherry",
  "Punjab Engineering College University of Technology",
  "Purnea College of Engineering",
  "R V College of Engineering",
  "R V S College of Engineering and Technology",
  "Radha Govind University",
  "Raghu Engineering College",
  "Raipur Institute of Technology",
  "Rajagiri School of Engineering & Technology",
  "Rajalakshmi Engineering College",
  "Rajeev Gandhi Memorial College of Engineering and",
  "Rajiv Gandhi College of Engineering and Technology, Pondicherry",
  "Rajiv Gandhi Government Polytechnic",
  "Rajiv Gandhi govt. Engineering college -[RGGEC], Kangra",
  "Rajiv Gandhi Institute of Petroleum Technology",
  "Rajiv Gandhi Institute of Technology",
  "Rajiv Gandhi University",
  "Rajiv Gandhi University of Knowledge Technologies -[RGUKT]",
  "Rama University, Kanpur",
  "Ramaiah Institute of Technology",
  "Ramchandra Chandarvansi Institute of Technology",
  "Ramgarh Engineering College",
  "Ramgovind Institute of Technology, Kodarma",
  "Ramrao Adik Institute of Technology",
  "Rashtrakavi Ramdhari Singh Dinkar College of Engineering",
  "Rashtrasant Tukadoji Maharaj Nagpur University",
  "Rayat Bahra University, Mohali",
  "Regency Institute of Technology, Yanam",
  "Regional Institute of Science and Technolog",
  "REVA University, Bangalore",
  "RIMT University, Gobindgarh",
  "RK University",
  "RKDF University, Bhopal",
  "RKDF University, Ranchi",
  "Royal Global University",
  "Royal School of Engineering and Technology",
  "RP Sharma Institute of Technology, Patna",
  "RSR Rungta College of Engineering and Technology",
  "RTC Institute of Technology",
  "Rungta College of Engineering and Technology",
  "Sagi Ramakrishnam Raju Engineering College",
  "Saharsa College of Engineering",
  "Sahrdaya College of Engineering",
  "Sai Nath University, Ranchi",
  "Saintgits College of Engineering, Kottayam",
  "Sandip University, Madhuban",
  "Sanskriti University",
  "Sant Baba Bhag Singh University",
  "Sant Longowal Institute of Engineering and Technology",
  "Sarala Birla University",
  "Sardar Patel College of Engineering",
  "Sardar Patel Institute of Technology",
  "Sardar Patel University",
  "Sardar Vallabhbhai National Institute of Technology",
  "SASTRA University, Thanjavur",
  "Saveetha Engineering College",
  "Scholar's Institute of Technology and Management",
  "School of Engineering and Technology, NCU",
  "Seacom Skills University",
  "Seemanta Engineering College, Mayurbhanj",
  "Seth Jai Parkash Mukand Lal Institute of",
  "Sharda University",
  "Sher-e-Kashmir University of Agricultural Sciences and Technology",
  "Shershah College of Engineering",
  "Shillong Polytechnic, Mawlai",
  "Shiv Nadar University",
  "Shiva Group of Institutions, Bilaspur",
  "Shivalik College of Engineering",
  "Shobhit University, Meerut",
  "Shree Rayeshwar Institute of Engineering and Information Technology, North Goa",
  "Shri Govindram Seksaria Institute of Technology and",
  "Shri Mata Vaishno Devi University",
  "Shri Ramdeobaba College of Engineering and Management",
  "Shri Rawatpura Sarkar University",
  "Shri Shankaracharya Group of Institutions",
  "Shri Shankaracharya Institute of Professional Management and",
  "Shri Vishnu Engineering College for Women",
  "Shridhar University, Pilani",
  "Siddaganga Institute of Technology",
  "Sikkim Manipal University",
  "Silicon Institute of Technology",
  "Siliguri Institute of Technology",
  "Singhania University, Jhunjhunu",
  "Sister Nivedita University",
  "Sitamarhi Institute of Technology",
  "Sityog Institute of Technology, Aurangabad",
  "Sona College of Technology, Salem",
  "Sree Chitra Thirunal College of Engineering",
  "Sree Vidyanikethan Engineering College",
  "Sreenidhi Institute of Science and Technology",
  "Sri Chakra Maritime College, Pondicherry",
  "Sri Guru Granth Sahib World University",
  "Sri Jayachamarajendra College of Engineering",
  "Sri Krishna College of Engineering and Technology",
  "Sri Manakula Vinayagar Engineering College, Pondicherry",
  "Sri Manakula Vinayagar Polytechnic College-[SMVPC], Pondicherry",
  "Sri Ramakrishna Engineering College",
  "Sri Sai University",
  "Sri Sairam Engineering College, Chennai",
  "Sri Vasavi Engineering College",
  "Sri Venkateswara College of Engineering",
  "Sri Venkateswara College of Engineering and Technology",
  "Sri Venkateswara University College of Engineering, Tirupati",
  "SRM Engineering College, Kanchipuram",
  "SRM University Delhi NCR, Sonepat",
  "SRM University Sikkim, Gangtok",
  "SSM College of Engineering and Technology",
  "SSN College of Engineering",
  "St Martin's Engineering College, Secunderabad",
  "St. Andrews Institute of Technology and Management",
  "St. Joseph College Of Engineering, Kanchipuram",
  "St. Thomas College of Engineering and Technology-",
  "St.Joseph University, Dimapur",
  "Starex University, Gurgaon",
  "SunRise University",
  "Supaul College of Engineering",
  "Suresh Gyan Vihar University",
  "Sushant University / Ansal University, Gurgaon",
  "SVKM's Narsee Monjee Institute of Management Studies",
  "Swami Keshvanand Institute of Technology, Management and",
  "Swami Rama Himalayan University",
  "Swami Vivekanand Group Of Institutes",
  "Swami Vivekanand Industrial Training Centre",
  "Swami Vivekanand Institute of Engineering & Technology",
  "Swami Vivekanand Polytechnic College",
  "Swami Vivekanand University, Sagar",
  "Tamil Nadu Veterinary and Animal Sciences University",
  "Tantia University, Sriganganagar",
  "Tata Institute of Social Sciences",
  "Techno College of Engineering Agartala",
  "Techno India Salt Lake, Kolkata",
  "Techno India University, Kolkata",
  "Tezpur University",
  "Tezpur University, School of Engineering Tezpur, Sonitpur",
  "Thakur College of Engineering and Technology",
  "Thapar Institute of Engineering and Technology",
  "THDC Institute of Hydro Power Engineering and",
  "The Global Open University",
  "The Global University, Itanagar",
  "The National Institute of Engineering",
  "The Neotia University",
  "Thejus Engineering College, Thrissur",
  "Thiagarajar College of Engineering",
  "TKM College of Engineering",
  "Tomi Polytechnic College, Basar",
  "Trident Academy of Technology, Bhubaneswar",
  "Trinity College of Engineering, Trivendrum",
  "Tripura Institute of Technology, Agartala",
  "Tripura University, West Tripura",
  "TTAADC Polytechnic Institute, West Tripura",
  "Tula's Institute, Dehradun",
  "Tura Polytechnic College, Tura",
  "Ujjain Engineering College",
  "Uka Tarsadia University, Bardoli",
  "Universal Polytechnic College, Chandigarh",
  "University College of Engineering and Technology, Vinoba",
  "University College of Engineering, Osmania University",
  "University Institute of Engineering and Technology -[UIET]",
  "University Institute of Engineering and Technology, Maharshi",
  "University Institute of Engineering, Chandigarh University",
  "University Institute of Information Technology, Himachal Pradesh",
  "University Institute of Technology, Rajiv Gandhi Proudyogiki",
  "University Institute of Technology, University Of Burdwan",
  "University of Engineering and Management",
  "University of Kashmir",
  "University of Petroleum and Energy Studies",
  "Vaagdevi College of Engineering",
  "Vallurupalli Nageswara Rao Vignana Jyothi Institute of",
  "Vardhaman College of Engineering",
  "Vasavi College of Engineering",
  "Veer Surendra Sai University of Technology",
  "Veermata Jijabai Technological Institute",
  "VEL Tech, Chennai",
  "Velagapudi Ramakrishna Siddhartha Engineering College",
  "Vellore Institute of Technology",
  "Venkateshwara Open University",
  "Vidya Memorial Institute of Technology",
  "Vidya Vihar Institute of Technology",
  "Vignan Institute of Technology And Management, Berhampur",
  "Vignan’s Foundation for Science, Technology, and Research",
  "Vinayaka Missions Sikkim University",
  "Vishwakarma Government Engineering College",
  "Vishwakarma Institute of Information Technology",
  "Vishwakarma Institute of Technology, Pune",
  "Visvesvaraya National Institute of Technology",
  "VIT Bhopal University, Bhopal",
  "VIT University",
  "Walchand College of Engineering",
  "William Carey University",
  "Women Institute of Technology",
  "Women’s Polytechnic College",
  "Xavier University",
  "YBN University",
  "Yeshwantrao Chavan College of Engineering",
  "Yogananda College of Engineering & Technology -[YCET]",
  "Other",
] as const;

export type University = typeof UNIVERSITIES[number];
